version: '2'
services:
    jhgrad180714-app:
        image: jhgrad180714
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhgrad180714-postgresql:5432/jhgrad180714
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhgrad180714-postgresql:
        extends:
            file: postgresql.yml
            service: jhgrad180714-postgresql
