version: '2'
services:
    jhgrad180714-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/jhgrad180714/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhgrad180714
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
